[package]
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
description = "A binding generator for Rust"
documentation = "https://crabtw.github.io/rust-bindgen/bindgen/index.html"
homepage = "https://github.com/crabtw/rust-bindgen"
keywords = ["bindings", "ffi", "code-generation"]
license = "BSD-3-Clause"
name = "bindgen"
readme = "README.md"
repository = "https://github.com/crabtw/rust-bindgen"
version = "0.19.0"

[[bin]]
doc = false
name = "bindgen"

[dependencies]
clang-sys = { version = "~0.11.0", features = ["clang_3_9"] }
# only for main, see https://github.com/rust-lang/cargo/issues/1982
docopt = "~0.6.80"
# only for main, see https://github.com/rust-lang/cargo/issues/1982
env_logger = "~0.3.3"
libc = "~0.2.11"
log = "~0.3.6"
# only for main, see https://github.com/rust-lang/cargo/issues/1982
rustc-serialize = "~0.3.19"
syntex_syntax = "~0.38.0"
cexpr = "0.2.0"

[dependencies.clippy]
optional = true
version = "0.0.95"

[dev-dependencies]
diff = "~0.1.9"
lazy_static = "0.2"

[features]
static = ["clang-sys/static"]

[[test]]
name = "tests"
